apiVersion: v1
kind: Service
metadata:
  name: cdk-web
  namespace: sbt-app
  labels:
    app: cdk-web
spec:
  type: ClusterIP
  selector:
    app: cdk-web
  ports:
    - name: http
      port: 80
      targetPort: 3000
